~/Downloads/mpy-cross/mpy-cross __init__.py
~/Downloads/mpy-cross/mpy-cross constants.py
~/Downloads/mpy-cross/mpy-cross device_registration.py
~/Downloads/mpy-cross/mpy-cross hmac.py
~/Downloads/mpy-cross/mpy-cross iot_error.py
~/Downloads/mpy-cross/mpy-cross iot_mqtt.py
~/Downloads/mpy-cross/mpy-cross iotcentral_device.py
~/Downloads/mpy-cross/mpy-cross iothub_device.py
~/Downloads/mpy-cross/mpy-cross keys.py
~/Downloads/mpy-cross/mpy-cross quote.py
~/Downloads/mpy-cross/mpy-cross base64.py